import Image from "next/image";

export default function Policy () {
    return (
        <main>
            <section className="text">
                <div className="container text__container">
                    <h2 className="text__headline">
                        Privacy Policy
                    </h2>
                    <Image
                        width={1000}
                        height={1000}
                        alt="policy img"
                        className="text__img"
                        src="/img/texture.jpg"
                    />
                    <div className="text__box">
                        <p>
                            OPTIMIZE CORPORATION LLC operates https://opti-corp.com (the Site)
                            This page informs you of OPTIMIZE CORPORATION LLC ’s policies regarding the collection, use, and disclosure of personal data when you use the Site and the choices you have associated with that data. OPTIMIZE CORPORATION LLC uses your data to provide and improve OPTIMIZE CORPORATION LLC Services.
                            By using the Site, you agree to the collection and use of information in accordance with this policy.
                        </p>
                    </div>
                    <div className="text__wrapper">

                        <h5 className="text__title">
                            Definitions “Personal Data”
                        </h5>
                        <p className="text__regular">
                            means data about an individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                        </p>

                        <h5 className="text__title">
                            “Usage Data”
                        </h5>
                        <p className="text__regular">
                            means data collected automatically either generated by the use of the Site or from OPTIMIZE CORPORATION LLC Services (for example, the duration of a page visit).
                        </p>

                        <h5 className="text__title">
                            “Cookies”
                        </h5>
                        <p className="text__regular">
                            means small pieces of data stored on your device (computer or mobile device).
                        </p>

                        <h5 className="text__title">
                            “Data Controller”
                        </h5>
                        <p className="text__regular">
                            means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, OPTIMIZE CORPORATION LLC is a Data Controller of your Personal Data.
                        </p>

                        <h5 className="text__title">
                            “Data Processors”
                        </h5>
                        <p className="text__regular">
                            means any natural or legal person who processes the data on behalf of the Data Controller. OPTIMIZE CORPORATION LLC may use the services of various Data Processors in order to process your data more effectively.
                        </p>

                        <h5 className="text__title">
                            “Data Subject”
                        </h5>
                        <p className="text__regular">
                            is any individual who is using OPTIMIZE CORPORATION LLC Services or visiting the Site and is the subject of Personal Data. Information Collection And Use We collect several different types of information for various purposes to provide and improve OPTIMIZE CORPORATION LLC Services
                            to you.
                        </p>

                        <h5 className="text__title">
                            Collection and usage
                        </h5>
                        <p className="text__regular">
                            We collect several different types of data for different purposes to improve OPTIMIZE CORPORATION LLC services for you.
                        </p>

                        <h5 className="text__title">
                            Types of Data Collected
                        </h5>
                        <p className="text__regular">
                            While using the Site, OPTIMIZE CORPORATION LLC may ask you to provide us with certain personally identifiable information that can be used to contact or identify you and to get benefits from personal access to OPTIMIZE CORPORATION LLC Services. Personally identifiable information may include, but is not limited to:
                        </p>
                        <ul className="text__list">
                            <li>
                                Email;
                            </li>
                            <li>
                                Name and surname;
                            </li>
                            <li>
                                Address;
                            </li>
                            <li>
                                Personal ID document (passport, driving license);
                            </li>
                            <li>
                                Age.
                            </li>
                        </ul>
                        <p className="text__regular">
                            OPTIMIZE CORPORATION LLC may use your Personal Data to contact you with newsletters, marketing or promotional materials, offers of OPTIMIZE CORPORATION LLC and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the instructions provided in any email we send or by contacting us. Usage Data OPTIMIZE CORPORATION LLC may also collect information that your browser sends whenever you visit the Site or when you access OPTIMIZE CORPORATION LLC Services. This Usage Data may include information such as your computer`&apos`s IP address, browser type, browser version, the pages of the Site that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When you access the Site by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                        </p>

                        <h5 className="text__title">
                            Tracking Cookies Data
                        </h5>
                        <p className="text__regular">
                            OPTIMIZE CORPORATION LLC uses cookies and similar tracking technologies to track the activity on the Site and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from the Site and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of the Website.
                        </p>

                        <h5 className="text__title">
                            Data usage
                        </h5>
                        <p className="text__regular">
                            Use of Data OPTIMIZE CORPORATION LLC uses the collected data for various purposes:
                        </p>
                        <ul>
                            <li>
                                To provide and maintain OPTIMIZE CORPORATION LLC Services;
                            </li>
                            <li>
                                To notify you about changes to OPTIMIZE CORPORATION LLC Services;
                            </li>
                        </ul>
                        <p className="text__regular">
                            Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR) If you are from the European Economic Area (EEA).
                        </p>
                        <p className="text__regular">
                            You have given OPTIMIZE CORPORATION LLC permission to do so:
                        </p>
                        <ul>
                            <li>
                                You are intended to become a OPTIMIZE CORPORATION LLC customer;
                            </li>
                            <li>
                                For cryptocurrency payment processing purposes;
                            </li>
                            <li>
                                To comply with the applicable laws.
                            </li>
                        </ul>

                        <h5>
                            Storage of data
                        </h5>
                        <p>
                            Retention of Data OPTIMIZE CORPORATION LLC will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. OPTIMIZE CORPORATION LLC will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. OPTIMIZE CORPORATION LLC will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                        </p>

                        <h5>
                            Data transfer
                        </h5>
                        <p>
                            Transfer Of Data Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction. OPTIMIZE CORPORATION LLC will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                        </p>
                        <p>
                            Disclosure Of Data Business Transaction If OPTIMIZE CORPORATION LLC is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy. Disclosure for Law Enforcement Under certain circumstances, OPTIMIZE CORPORATION LLC may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency). Legal Requirements OPTIMIZE CORPORATION LLC may disclose your Personal Data in the good faith belief that such action is necessary to:
                        </p>
                        <ul>
                            <li>
                                To comply with a legal obligation;
                            </li>
                        </ul>

                        <h5>
                            Disclosure of data
                        </h5>
                        <ul>
                            <li>
                                To protect and defend the rights or property of OPTIMIZE CORPORATION LLC;
                            </li>
                        </ul>

                        <h5>
                            Business transaction
                        </h5>
                        <ul>
                            <li>
                                To prevent or investigate possible wrongdoing in connection with OPTIMIZE CORPORATION LLC Services;
                            </li>
                            <li>
                                To protect the personal safety of OPTIMIZE CORPORATION LLC;
                            </li>
                        </ul>
                        <p>
                            If OPTIMIZE CORPORATION LLC is involved in a merger, acquisition or asset sale, your personal data may be transferred. We will notify you before your personal data is transferred and becomes subject to a different Privacy Policy.
                        </p>

                        <h5>
                            Disclosure of information for law enforcement agencies
                        </h5>

                        <h5>
                            Security Of Data
                        </h5>
                        <p>
                            The security of your data is important to OPTIMIZE CORPORATION LLC , but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While OPTIMIZE CORPORATION LLC strives to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                        </p>

                        <h5>
                            Legal requirements of the law
                        </h5>
                        <p>
                            OPTIMIZE CORPORATION LLC may disclose your Personal Data if such actions are necessary to:
                        </p>
                        <ul>
                            <li>
                                compliance with legal obligations;
                            </li>
                            <li>
                                protecting the rights of OPTIMIZE CORPORATION LLC;
                            </li>
                            <li>
                                preventing or investigating possible violations in connection with the provision of OPTIMIZE CORPORATION LLC services;
                            </li>
                            <li>
                                protecting the personal safety of OPTIMIZE CORPORATION LLC;
                            </li>
                            <li>
                                protection from legal liability.
                            </li>
                        </ul>

                        <h5>
                            Data security
                        </h5>
                        <p>
                            The security of your data is important to OPTIMIZE CORPORATION LLC, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. Although OPTIMIZE CORPORATION LLC strives to use reasonable means to protect your personal data, we cannot guarantee its absolute security.
                            Your Data Protection Rights Under General Data Protection Regulation (GDPR)
                            If you are a resident of the European Economic Area (EEA), you have certain data protection rights. OPTIMIZE CORPORATION LLC aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data. If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us. In certain circumstances, you have the following data protection rights:
                        </p>
                        <ul>
                            <li>
                                The right to access, update or to delete the information on you. Whenever made possible, you can access, update or request deletion of your Personal Data. If you are unable to perform these actions yourself, please contact OPTIMIZE CORPORATION LLC support to assist you.
                            </li>
                            <li>
                                The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.
                            </li>
                            <li>
                                The right to object. You have the right to object to OPTIMIZE CORPORATION LLC’s processing of your Personal Data.
                            </li>
                            <li>
                                The right of restriction. You have the right to request that OPTIMIZE CORPORATION LLC restricts the processing of your personal information.
                            </li>
                            <li>
                                The right to data portability. You have the right to be provided with a copy of the information OPTIMIZE CORPORATION LLC has on you in a structured, machine-readable and commonly used format.
                            </li>
                            <li>
                                The right to withdraw consent. You also have the right to withdraw your consent at any time where OPTIMIZE CORPORATION LLC relied on your consent to process your personal information.
                            </li>
                        </ul>
                        <p>
                            Please note that OPTIMIZE CORPORATION LLC may ask you to verify your identity before responding to such requests.
                        </p>

                        <h5>
                            Links To Other Sites
                        </h5>
                        <p>
                            The Site may contain links to other sites that are not operated by OPTIMIZE CORPORATION LLC . If you click on a third party link, you will be directed to that third party`&apos`s site. OPTIMIZE CORPORATION LLC strongly advises you to review the privacy policy of every site you visit OPTIMIZE CORPORATION LLC has no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                        </p>

                        <h5>
                            Changes in this Privacy Policy
                        </h5>
                        <p>
                            Changes To This Privacy Policy OPTIMIZE CORPORATION LLC may update our Privacy Policy from time to time. OPTIMIZE CORPORATION LLC will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                        </p>
                        <p>
                            Contact OPTIMIZE CORPORATION LLC If you have any questions about this Privacy Policy.
                        </p>

                    </div>
                </div>
            </section>
        </main>
    )
}
